pragma ComponentBehavior: Bound
// Nyxus Suxyn — Settings ▸ System ▸ Reset.                         TRK-1261
//
// The one place that resets EVERYTHING, and the page that says what the
// settings file is (where it lives, which schema it is at, what was backed
// up). Per-page resets live at the bottom of the pages themselves
// (`SetResetRow`); this page links to them rather than duplicating them.
//
// "Reset all settings" is the dangerous one: it backs the file up FIRST
// (`settings.json.bak-reset-<stamp>`), then writes a fresh file holding only
// `schema_version`. Every key — the shell's AND the GTK control center's,
// which share the file — falls back to its shipped default. It says so,
// because a reset that quietly takes the control center's settings with it
// is a surprise, and two taps are the price of it (SetButton `danger`).
import Quickshell
import QtQuick
import QtQuick.Layouts

SetPage {
    id: page
    property var entry: null
    title: qsTr("Reset")
    blurb: qsTr("Back to the shipped defaults — one page at a time, or all of it.")

    readonly property int keyCount: {
        var d = SettingsStore.doc;
        var n = 0;
        for (var k in d)
            if (k !== "schema_version")
                ++n;
        return n;
    }

    // Output of the last dry run, one line per change, for the card below.
    property string dryRunText: ""

    SetCard {
        heading: qsTr("The settings file")
        tone: page.tone
        note: qsTr("One file, ~/.config/nyxus/settings.json — the shell and the GTK control center both read and write it. Removing a key puts that setting back to what a fresh install has.")

        SetRow {
            glyph: ""
            title: qsTr("Where it is")
            sub: SettingsStore.path
            valueText: SettingsStore.loaded
                       ? (SettingsStore.parseError !== "" ? "unreadable"
                          : (page.keyCount === 0 ? "defaults"
                             : page.keyCount + (page.keyCount === 1 ? " key" : " keys")))
                       : "reading…"
        }

        SetRow {
            glyph: ""
            title: qsTr("Schema")
            sub: SettingsStore.schemaVersion === SettingsStore.schemaCurrent
                 ? "Version " + SettingsStore.schemaVersion + " — current. Older files are migrated on load, after a backup."
                 : (SettingsStore.schemaVersion > SettingsStore.schemaCurrent
                    ? "Version " + SettingsStore.schemaVersion + " is NEWER than this shell's " + SettingsStore.schemaCurrent + ". Left untouched."
                    : "Version " + SettingsStore.schemaVersion + " — will migrate to " + SettingsStore.schemaCurrent + " on the next load.")
            valueText: "v" + SettingsStore.schemaVersion
        }

        SetRow {
            glyph: ""
            title: qsTr("Last backup")
            sub: SettingsStore.lastBackup === ""
                 ? "None this session. A backup is written beside the file before any migration or full reset."
                 : SettingsStore.lastBackup
        }

        SetRow {
            glyph: ""
            title: qsTr("Dry-run the migration")
            sub: page.dryRunText === ""
                 ? "Lists what a migration would change in the file now, and changes nothing."
                 : page.dryRunText

            SetButton {
                text: qsTr("Dry run")
                glyph: ""
                tone: page.tone
                onClicked: page.dryRunText = SettingsStore.migrationDryRun()
            }
        }
    }

    SetCard {
        heading: qsTr("One page at a time")
        tone: page.tone
        // ── audit-0908 · TRK-3965 ───────────────────────────────────────
        // This card used to be five hand-written rows: Accessibility,
        // Appearance, Background, Notifications, Keep awake. It was wrong in
        // both directions at the same time, which is the shape of every
        // hand-copied list here.
        //
        //   * On the owner's deployed shell SIXTEEN pages had a Reset row.
        //     Eleven of them were unreachable from the one page whose whole
        //     job is to tell you where the resets are.
        //   * And in this tree the first row named Accessibility, which has
        //     NO reset row — a link that promises a control that is not
        //     there, which is worse than an omission.
        //
        // There is also no number to correct once and be done: it was 7 on
        // `main`, 8 on the branch that fixed this and 16 on the live shell in
        // the same week, because adding the row is a manual per-page step.
        //
        // So the card stops naming pages. `SettingsIndex.resetPages` is
        // generated by `scripts/gen-settings-index.py` from the pages
        // themselves — a page is in it because it contains a `SetResetRow`
        // element, the same thing that puts the row on screen — and gate
        // 13w60 regenerates the index and fails if the committed copy has
        // drifted. The list here can no longer be wrong without the page
        // itself being wrong.
        note: SettingsIndex.resetPageCount > 0
              ? qsTr("Each of these pages has a Reset row at the bottom that clears only its own keys. Counted from the pages, not typed here.")
              : qsTr("No page in this build carries its own Reset row — everything below resets the whole file.")

        Repeater {
            model: SettingsIndex.resetPages
            delegate: SetRow {
                required property var modelData
                glyph: ""
                title: modelData.label
                sub: modelData.sub
                navigates: true
                onActivated: Bus.openSettings(modelData.key)
            }
        }
    }

    SetCard {
        heading: qsTr("Everything")
        tone: page.tone
        note: qsTr("Backs the file up beside itself, then writes a fresh one. The GTK control center's settings live in the same file and reset with it. Two taps.")

        SetRow {
            glyph: ""
            title: qsTr("Reset all settings")
            sub: page.keyCount === 0
                 ? "The file already holds nothing but its schema version."
                 : (page.keyCount === 1 ? "One key" : page.keyCount + " keys")
                   + " will be removed after a backup to settings.json.bak-reset-<stamp>."

            SetButton {
                text: qsTr("Reset all")
                glyph: ""
                danger: true
                enabled: page.keyCount > 0 && SettingsStore.loaded
                confirmText: qsTr("Reset everything")
                onClicked: SettingsStore.resetAll()
            }
        }
    }
}
