# The broadcom-wl package requires some modules to be disabled in order to
# function correctly. They are listed here so the default install will work
# out of the box.
blacklist b43
blacklist b43legacy
blacklist ssb
blacklist bcm43xx
blacklist brcm80211
blacklist brcmfmac
blacklist brcmsmac
blacklist bcma
