#!/usr/bin/env python3
"""Nyxus Suxyn — settings search-index drift checker.

WHY THIS EXISTS, AND WHY IT IS NOT A GENERATOR ───────────────── TRK-4142 ──

`quickshell/SettingsIndex.qml` carries this header:

    GENERATED by `scripts/gen-settings-index.py` from `shell/SetPage*.qml`.
    DO NOT HAND-EDIT: `scripts/audit.sh` gate 13w60 regenerates this file
    and fails if the committed copy differs.

Neither script has ever been in this repo. Searched the tree and the whole
home directory on 2026-09-14, and PATH as well: no `scripts/`, no
gen-settings-index.py, no audit.sh. So `SettingsIndex.qml` was a generated
artifact with no generator and no gate, which means the "do not hand-edit"
rule could not be obeyed even by someone who wanted to.

The damage was already done by the time anyone looked. Checking the toast
Corner control on SetPageNotifications.qml against its index entries:

    on the page     Corner / Where toasts rise from
                    Bottom right · Bottom left · Top right · Top left
    in the index    BOTTOM RIGHT / "Rises out of the Line"
                    BOTTOM LEFT  / "The other Line corner"
                    TOP RIGHT    / "Away from the Line"

Three of those subs do not appear anywhere in the page. "Top left" is not
indexed at all, and neither is the Corner row itself — so typing "corner"
into Settings search finds nothing, which is TRK-3567 all over again: a
setting nobody can find is indistinguishable from one that does not exist.

Rebuilding the original generator would mean reproducing 527 entries across
34 pages byte-for-byte, including whatever hand-edits have accumulated since
it disappeared. That is a lot of guessing to arrive at a file we already
have. The thing that was actually missing is the GATE — something that fails
when a page and its index disagree. So this is a checker, not a generator:
it does not rewrite the index, it tells you exactly where the index and the
pages have come apart, and it exits non-zero so it can be wired into CI.

Adding a control still means adding its index entry by hand. The difference
is that forgetting is now loud instead of silent.

USAGE
    scripts/check-settings-index.py            # full drift report, exit 1 if any
    scripts/check-settings-index.py --emit     # entries for anything missing
    scripts/check-settings-index.py --quiet    # exit code only
    scripts/check-settings-index.py --key sound

THE GATE IS `--emit`, NOT THE PLAIN REPORT ─────────────────────────────────

Wire CI to `--emit`: it exits 0 only when every component-level control on
every page already has an index entry, and prints ready-to-paste QML when it
does not. That is the condition worth failing a build over.

The plain report is deliberately noisier and will not reach zero. It walks
every translatable property on a page, so it also lists prose — page
subtitles, empty-state messages, SetIceFace `detail` lines like "That
normally means this shell is not running under Hyprland." Those are not
things anyone searches for by name, and indexing them would make short
queries match paragraphs. After the TRK-4142 recovery the report still shows
~106 such strings; that is the floor, not a backlog.

The ~121 "stale" entries are left alone on purpose. An index entry whose
text no longer appears on its page still routes a search to the right page,
so it behaves as a synonym. Deleting them can only lose matches.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
QML = REPO / "quickshell"
CATALOGUE = QML / "SettingsCatalog.qml"
INDEX = QML / "SettingsIndex.qml"

# Properties whose qsTr() value becomes a searchable label or sub. Anything
# else on a page (bindings, ids, colours) is not user-facing text.
INDEXED_PROPS = (
    "title", "sub", "heading", "note", "kicker", "caption",
    "detail", "text", "label", "blurb", "placeholder",
)

PROP_RE = re.compile(
    r"\b(?P<prop>" + "|".join(INDEXED_PROPS) + r")\s*:\s*"
    r"qsTr\(\s*(?P<q>[\"'])(?P<text>(?:\\.|(?!(?P=q)).)*)(?P=q)"
)
# Options arrays read `{ value: "x", label: qsTr("Y") }` — the prop regex
# above already catches those, since `label:` is in the list.

CAT_ENTRY_RE = re.compile(
    r"\{\s*key:\s*\"(?P<key>[a-z0-9_]+)\"\s*,\s*title:\s*qsTr\(\s*\"(?P<title>(?:\\.|[^\"])*)\"\s*\)"
    r".*?blurb:\s*qsTr\(\s*\"(?P<blurb>(?:\\.|[^\"])*)\"\s*\)"
    r".*?page:\s*\"(?P<page>SetPage[A-Za-z0-9]+\.qml)\"",
    re.S,
)

IDX_ENTRY_RE = re.compile(
    r"\{\s*key:\s*\"(?P<key>[a-z0-9_]+)\"\s*,\s*kind:\s*\"(?P<kind>[a-z]+)\"\s*,\s*"
    r"label:\s*qsTranslate\(\s*\"(?P<ctx>[A-Za-z0-9]+)\"\s*,\s*"
    r"(?P<lq>[\"'])(?P<label>(?:\\.|(?!(?P=lq)).)*)(?P=lq)",
    re.S,
)

IDX_SUB_RE = re.compile(
    r"sub:\s*qsTranslate\(\s*\"[A-Za-z0-9]+\"\s*,\s*"
    r"(?P<q>[\"'])(?P<sub>(?:\\.|(?!(?P=q)).)*)(?P=q)"
)


def strip_comments(src: str) -> str:
    """Drop // line comments and /* */ blocks without eating string bodies.

    A naive `//` strip corrupts any label containing a URL or a path, and
    several pages have both, so walk the source once in a tiny state machine
    instead of reaching for a regex that cannot know what a string is.
    """
    out = []
    i, n = 0, len(src)
    quote = None
    while i < n:
        c = src[i]
        nxt = src[i + 1] if i + 1 < n else ""
        if quote:
            out.append(c)
            if c == "\\" and nxt:
                out.append(nxt)
                i += 2
                continue
            if c == quote:
                quote = None
            i += 1
            continue
        if c in "\"'":
            quote = c
            out.append(c)
            i += 1
            continue
        if c == "/" and nxt == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if c == "/" and nxt == "*":
            i += 2
            while i + 1 < n and not (src[i] == "*" and src[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def unescape(s: str) -> str:
    return s.replace('\\"', '"').replace("\\'", "'").replace("\\\\", "\\")


def page_strings(path: Path) -> dict[str, str]:
    """Searchable text on a page -> the property it came from.

    Flat property scanning, used for the DRIFT report where all that matters
    is whether a string is reachable by search at all.
    """
    src = strip_comments(path.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for m in PROP_RE.finditer(src):
        text = unescape(m.group("text")).strip()
        if text:
            out.setdefault(text, m.group("prop"))
    return out


# component -> (kind, label property, sub property). Read back off the
# committed index rather than invented: SetCard heading/note pairs appear
# there as sections, SetButton text as actions, and SetRow / SetIceFace
# field pairs as controls.
COMPONENTS = {
    "SetCard":    ("section", "heading", "note"),
    "SetRow":     ("control", "title", "sub"),
    "SetIceFace": ("control", "kicker", "caption"),
    "SetButton":  ("action", "text", None),
}
NESTED_RE = re.compile(r"\b(?:" + "|".join(COMPONENTS) + r")\s*\{")
OPTION_LABEL_RE = re.compile(
    r"\blabel\s*:\s*qsTr\(\s*(?P<q>[\"'])(?P<text>(?:\\.|(?!(?P=q)).)*)(?P=q)"
)


def _match_brace(src: str, open_idx: int) -> int:
    """Index of the `}` closing the `{` at open_idx, ignoring braces in strings.

    Several pages put `{` inside label text (keyboard hints, format strings),
    so a plain depth counter walks off the end of the file.
    """
    depth, i, n, quote = 0, open_idx, len(src), None
    while i < n:
        c = src[i]
        if quote:
            if c == "\\":
                i += 2
                continue
            if c == quote:
                quote = None
        elif c in "\"'":
            quote = c
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return n - 1


def page_entries(path: Path) -> list[tuple[str, str, str]]:
    """(kind, label, sub) for every indexable component on a page.

    Only the block HEAD is read — the text before the first nested component
    — so a SetCard does not swallow the titles of the SetRows inside it and
    report them as its own note.
    """
    src = strip_comments(path.read_text(encoding="utf-8"))
    entries: list[tuple[str, str, str]] = []
    seen: set[tuple[str, str]] = set()

    for name, (kind, lprop, sprop) in COMPONENTS.items():
        for m in re.finditer(r"\b" + name + r"\s*\{", src):
            open_idx = m.end() - 1
            block = src[open_idx:_match_brace(src, open_idx)]
            nested = NESTED_RE.search(block, 1)
            head = block[: nested.start()] if nested else block

            def grab(prop: str) -> str:
                if not prop:
                    return ""
                g = re.search(
                    r"\b" + prop + r"\s*:\s*qsTr\(\s*([\"'])((?:\\.|(?!\1).)*)\1",
                    head,
                )
                return unescape(g.group(2)).strip() if g else ""

            label = grab(lprop)
            if not label:
                continue
            sub = grab(sprop)
            if (label, sub) not in seen:
                seen.add((label, sub))
                entries.append((kind, label, sub))

    # SetChoice options are `{ value: "x", label: qsTr("Y") }` — no sub.
    for m in OPTION_LABEL_RE.finditer(src):
        label = unescape(m.group("text")).strip()
        if label and (label, "") not in seen:
            seen.add((label, ""))
            entries.append(("control", label, ""))

    return entries


KIND_BY_PROP = {
    "heading": "section",
    "note": "section",
    "blurb": "section",
    "text": "action",
}


def qml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def index_strings() -> dict[str, set[str]]:
    src = INDEX.read_text(encoding="utf-8")
    body = src[src.index("readonly property var controls"):]
    found: dict[str, set[str]] = {}
    # Split on entry boundaries so each label keeps its own sub.
    for chunk in re.split(r"(?=\{\s*key:\s*\")", body):
        m = IDX_ENTRY_RE.search(chunk)
        if not m:
            continue
        key = m.group("key")
        bucket = found.setdefault(key, set())
        bucket.add(unescape(m.group("label")).strip())
        s = IDX_SUB_RE.search(chunk)
        if s:
            bucket.add(unescape(s.group("sub")).strip())
    return found


def catalogue() -> list[tuple[str, str, set[str]]]:
    """key -> page file, plus the title/blurb the CATALOGUE already indexes.

    `SettingsCatalog.search()` matches page titles and blurbs directly, so a
    string that is only ever a page's own title is findable without any
    SettingsIndex entry. Reporting those as unsearchable buried the real
    misses under one false positive per page.
    """
    src = strip_comments(CATALOGUE.read_text(encoding="utf-8"))
    out = []
    for m in CAT_ENTRY_RE.finditer(src):
        own = {unescape(m.group("title")).strip(),
               unescape(m.group("blurb")).strip()}
        out.append((m.group("key"), m.group("page"), own))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--quiet", action="store_true", help="exit code only")
    ap.add_argument("--key", help="check a single catalogue key")
    ap.add_argument("--emit", action="store_true",
                    help="print QML entries for everything NOT indexed, in "
                         "the committed format, ready to paste into the "
                         "controls list")
    args = ap.parse_args()

    for f in (CATALOGUE, INDEX):
        if not f.exists():
            print(f"FATAL: {f} not found", file=sys.stderr)
            return 2

    idx = index_strings()
    pages = catalogue()
    if args.key:
        pages = [p for p in pages if p[0] == args.key]
        if not pages:
            print(f"FATAL: no catalogue key {args.key!r}", file=sys.stderr)
            return 2

    total_missing = total_stale = 0
    report: list[str] = []
    emitted: list[str] = []

    for key, page, cat_own in pages:
        path = QML / page
        if not path.exists():
            report.append(f"  {key:<14} FATAL page missing: {page}")
            total_missing += 1
            continue
        page_map = page_strings(path)
        on_page = set(page_map)
        indexed = idx.get(key, set())
        # Catalogue title/blurb count as coverage for the MISSING check only.
        # They are not SettingsIndex entries, so they can never be stale ones.
        searchable = indexed | cat_own

        # Match exactly, or by PREFIX for long strings only.
        #
        # The index truncates a long sub at its qsTr literal — a page writes
        #   note: qsTr("Quiet stays on after a reload. In-shell timers ")
        #         + "honour it."
        # and the index stores just the quoted part — so the stored string is
        # a prefix of the page's. That is the only shape truncation takes.
        #
        # Plain containment was tried first and over-matched badly: the page's
        # "Corner" row was reported as indexed because the letters appear
        # inside a STALE entry reading "The other Line corner". Short labels
        # like Left, Right, Wait and Centre hide inside longer sentences all
        # over the file, so containment quietly marked real gaps as covered.
        # Prefix plus a 20-character floor keeps the truncation case and
        # drops the coincidences.
        def covered(s: str, pool: set[str]) -> bool:
            t = s.casefold()
            for p in (q.casefold() for q in pool if q):
                if t == p:
                    return True
                if len(p) >= 20 and t.startswith(p):
                    return True
                if len(t) >= 20 and p.startswith(t):
                    return True
            return False

        missing = sorted(s for s in on_page if s and not covered(s, searchable))
        stale = sorted(s for s in indexed if s and not covered(s, on_page))
        total_missing += len(missing)
        total_stale += len(stale)

        if args.emit:
            ctx = page[:-4]
            for kind, label, sub in page_entries(path):
                if covered(label, searchable):
                    continue
                subq = (f'qsTranslate("{ctx}", "{qml_escape(sub)}")'
                        if sub else '""')
                emitted.append(
                    f'        {{ key: "{key}", kind: "{kind}",\n'
                    f'          label: qsTranslate("{ctx}", "{qml_escape(label)}"),\n'
                    f'          sub: {subq} }},'
                )

        if missing or stale:
            report.append(
                f"  {key:<14} {page:<28} "
                f"unsearchable {len(missing):>3} · stale {len(stale):>3}"
            )
            for s in missing[:6]:
                report.append(f"      NOT INDEXED  {s[:68]!r}")
            if len(missing) > 6:
                report.append(f"      … and {len(missing) - 6} more")
            for s in stale[:4]:
                report.append(f"      STALE        {s[:68]!r}")
            if len(stale) > 4:
                report.append(f"      … and {len(stale) - 4} more")

    if args.emit:
        print("\n".join(emitted))
        return 1 if emitted else 0

    if not args.quiet:
        print("settings index drift — SettingsIndex.qml vs SetPage*.qml")
        print(f"checked {len(pages)} pages\n")
        print("\n".join(report) if report else "  no drift")
        print(
            f"\n  {total_missing} control strings are on a page but NOT searchable"
        )
        print(f"  {total_stale} index entries no longer exist on their page")

    return 1 if (total_missing or total_stale) else 0


if __name__ == "__main__":
    sys.exit(main())
